Repository fastly/go-fastly, pull requests merged in 2021-01, with the labels that each got.

#244 Reword expected error message based on API changes
  fastly/fixtures/managed_logging/recreate.yaml
Labels: bug

#248 Update to RequestMaxBytes to align with updated API and regenerate fixtures
  fastly/fixtures/kafkas/cleanup.yaml
  fastly/fixtures/kafkas/create.yaml
  fastly/fixtures/kafkas/delete.yaml
  fastly/fixtures/kafkas/get.yaml
  fastly/fixtures/kafkas/list.yaml
  fastly/fixtures/kafkas/update.yaml
  fastly/fixtures/kafkas/version.yaml
  fastly/kafka_test.go
Labels: bug

#246 Cleanup naming of Kinesis to be more consistent.
  fastly/fixtures/kinesis/cleanup.yaml
  fastly/fixtures/kinesis/create.yaml
  fastly/fixtures/kinesis/delete.yaml
  fastly/fixtures/kinesis/get.yaml
  fastly/fixtures/kinesis/list.yaml
  fastly/fixtures/kinesis/update.yaml
  fastly/fixtures/kinesis/version.yaml
  fastly/kinesis.go
  fastly/kinesis_test.go
Labels: bug

#247 Avoid generic ID field when more explicit naming would be clearer
  fastly/errors.go
  fastly/token.go
  fastly/token_test.go
Labels: enhancement

#243 Add region support to logentries logging endpoint
  fastly/fixtures/logentries/create.yaml
  fastly/fixtures/logentries/delete.yaml
  fastly/fixtures/logentries/get.yaml
  fastly/fixtures/logentries/list.yaml
  fastly/fixtures/logentries/update.yaml
  fastly/fixtures/logentries/version.yaml
  fastly/logentries.go
  fastly/logentries_test.go
Labels: enhancement

#239 Create new error abstraction for field validation
  README.md
  fastly/acl_entry.go
  fastly/acl_entry_test.go
  fastly/acl_test.go
  fastly/backend_test.go
  fastly/blobstorage_test.go
  fastly/cache_setting_test.go
  fastly/cloudfiles_test.go
  fastly/condition_test.go
  fastly/custom_tls_certificate_test.go
  fastly/custom_tls_configuration_test.go
  fastly/datadog_test.go
  fastly/dictionary_item.go
  fastly/dictionary_item_test.go
  fastly/dictionary_test.go
  fastly/diff_test.go
  fastly/digitalocean_test.go
  fastly/director_backend_test.go
  fastly/director_test.go
  fastly/domain_test.go
  fastly/errors.go
  fastly/ftp_test.go
  fastly/gcs_test.go
  fastly/gzip_test.go
  fastly/header_test.go
  fastly/health_check_test.go
  fastly/kinesis_test.go
  fastly/logentries_test.go
  fastly/loggly_test.go
  fastly/newrelic_test.go
  fastly/openstack_test.go
  fastly/papertrail_test.go
  fastly/pool_test.go
  fastly/pubsub_test.go
  fastly/request_setting_test.go
  fastly/response_object_test.go
  fastly/s3.go
  fastly/s3_test.go
  fastly/server.go
  fastly/server_test.go
  fastly/service.go
  fastly/service_test.go
  fastly/sftp_test.go
  fastly/sumologic_test.go
  fastly/user_test.go
  fastly/vcl_snippets_test.go
  fastly/vcl_test.go
  fastly/waf.go
  fastly/waf_active_rule.go
  fastly/waf_active_rule_test.go
  fastly/waf_rule_exclusion.go
  fastly/waf_rule_exclusion_test.go
  fastly/waf_test.go
  fastly/waf_version_test.go
  go.mod
Labels: enhancement

#249 Ensure consistent naming for ServiceID (fixes missed references)
  fastly/realtime_stats.go
  fastly/realtime_stats_test.go
  fastly/service.go
  fastly/service_test.go
Labels: bug

#250 Strip TLS prefix from TLS struct fields
  fastly/platform_tls.go
  fastly/platform_tls_test.go
Labels: enhancement

#251 Dictionary ItemValue isn't optional
  fastly/dictionary_item.go
  fastly/dictionary_item_test.go
Labels: bug

#252 NewName should be optional
  fastly/domain.go
  fastly/domain_test.go
Labels: bug

#254 Add important notes related to test fixtures and sensitive data.
  README.md
Labels: documentation

#255 Add support for file_max_bytes configuration for azure logging endpoint
  fastly/blobstorage.go
  fastly/blobstorage_test.go
  fastly/fixtures/blobstorages/cleanup.yaml
  fastly/fixtures/blobstorages/create.yaml
  fastly/fixtures/blobstorages/create2.yaml
  fastly/fixtures/blobstorages/create3.yaml
  fastly/fixtures/blobstorages/delete.yaml
  fastly/fixtures/blobstorages/get.yaml
  fastly/fixtures/blobstorages/list.yaml
  fastly/fixtures/blobstorages/update.yaml
  fastly/fixtures/blobstorages/update2.yaml
  fastly/fixtures/blobstorages/update3.yaml
  fastly/fixtures/blobstorages/version.yaml
Labels: enhancement
