Repository fastly/go-fastly, pull requests merged in 2022-11, with the labels that each got.

#377 Add google account name to all google logging endpoints
  fastly/bigquery.go
  fastly/bigquery_test.go
  fastly/fixtures/bigqueries/cleanup.yaml
  fastly/fixtures/bigqueries/create.yaml
  fastly/fixtures/bigqueries/delete.yaml
  fastly/fixtures/bigqueries/get.yaml
  fastly/fixtures/bigqueries/list.yaml
  fastly/fixtures/bigqueries/update.yaml
  fastly/fixtures/bigqueries/version.yaml
  fastly/fixtures/gcses/cleanup.yaml
  fastly/fixtures/gcses/create.yaml
  fastly/fixtures/gcses/create2.yaml
  fastly/fixtures/gcses/create3.yaml
  fastly/fixtures/gcses/create4.yaml
  fastly/fixtures/gcses/delete.yaml
  fastly/fixtures/gcses/get.yaml
  fastly/fixtures/gcses/list.yaml
  fastly/fixtures/gcses/update.yaml
  fastly/fixtures/gcses/update2.yaml
  fastly/fixtures/gcses/update3.yaml
  fastly/fixtures/gcses/version.yaml
  fastly/fixtures/pubsubs/cleanup.yaml
  fastly/fixtures/pubsubs/create.yaml
  fastly/fixtures/pubsubs/delete.yaml
  fastly/fixtures/pubsubs/get.yaml
  fastly/fixtures/pubsubs/list.yaml
  fastly/fixtures/pubsubs/update.yaml
  fastly/fixtures/pubsubs/version.yaml
  fastly/pubsub.go
  fastly/pubsub_test.go
Labels: enhancement

#379 Address FIXME notes
  fastly/errors.go
  fastly/service_authorization.go
  fastly/service_authorization_test.go
  fastly/waf_rules.go
  fastly/waf_rules_test.go
Labels: enhancement, breaking-change

#380 Ensure parameters are sent to API
  fastly/acl_entry.go
  fastly/acl_entry_test.go
  fastly/fixtures/acl_entries/acl.yaml
  fastly/fixtures/acl_entries/create.yaml
  fastly/fixtures/acl_entries/create_service.yaml
  fastly/fixtures/acl_entries/delete.yaml
  fastly/fixtures/acl_entries/delete_acl.yaml
  fastly/fixtures/acl_entries/delete_service.yaml
  fastly/fixtures/acl_entries/get.yaml
  fastly/fixtures/acl_entries/list.yaml
  fastly/fixtures/acl_entries/list2.yaml
  fastly/fixtures/acl_entries/update.yaml
  fastly/fixtures/acl_entries/version.yaml
  fastly/fixtures/services/cleanup.yaml
  fastly/fixtures/services/create.yaml
  fastly/fixtures/services/delete.yaml
  fastly/fixtures/services/details.yaml
  fastly/fixtures/services/domain.yaml
  fastly/fixtures/services/get.yaml
  fastly/fixtures/services/list.yaml
  fastly/fixtures/services/list_paginator.yaml
  fastly/fixtures/services/search.yaml
  fastly/fixtures/services/update.yaml
  fastly/request.go
  fastly/service.go
  fastly/service_test.go
Labels: bug
