Repository fastly/go-fastly, pull requests merged in 2022-01, with the labels that each got.

#323 Bump deps to side-step gopkg.in/yaml.v2 security vulnerability
  go.mod
  go.sum
Labels: enhancement

#328 Pagination to return interface not concrete type
  fastly/acl_entry.go
  fastly/acl_entry_test.go
  fastly/dictionary_item.go
  fastly/dictionary_item_test.go
  fastly/paginator.go
  fastly/service.go
  fastly/service_test.go
Labels: enhancement, breaking-change

#330 Correctly set and advance current page
  fastly/acl_entry.go
  fastly/dictionary_item.go
  fastly/service.go
Labels: bug
